Remove annoying error in log when running Manual Cycle
Second attempt.
This time I have added a line rather then deleting one by mistake...
The variable `trigger_time` can't be set for a manual cycle. There is no `trigger.now` when the trigger was caused by a state change.
The error in the log caused no harm but was annoying.

```
Logger: homeassistant.components.automation.irrigation_triggered
Source: components/automation/__init__.py:456
Integration: Automation (documentation, issues)
First occurred: 17:10:02 (3 occurrences)
Last logged: 17:28:04

Error rendering variables: UndefinedError: 'dict object' has no attribute 'now'
```